### ISSUE TITLE
Frequency configuration

### ISSUE THREAD

**Issue by gstevenson** [dan-r/HomeAssistant-Ohme#100]
After only installing the integration about 12 hours ago, it has already performed the most hits of any device on my entire network; 

https://i.imgur.com/vFBJlfd.png

It would be good to be able to customise the frequencies that are noted in [README.md](https://github.com/dan-r/HomeAssistant-Ohme?tab=readme-ov-file#coordinators) to tweak based on user preferences

**Comment by dan-r** [comment]
Thanks for reporting this - the reason it makes so many hits is that although the refresh times are in line with typical integrations, annoyingly the data needed comes from 4 different API endpoints.

I've released a beta (v1.0.1-beta.2) which allows the refresh intervals to be configured. Would you mind testing this out please?

Dan

**Comment by gstevenson** [comment]
Thanks, that was fast! Installed and configured, will keep an eye on the calls

**Comment by dan-r** [comment]
If you enable debug logging you'll also be able to see when the coordinators run and data is fetched. You'll probably have to filter the logs though as you'll get a lot!

**Comment by xenjke** [comment]
@gstevenson could you please let me know which tool you used to visualise the network calls? Thanks a bunch!

**Comment by gstevenson** [comment]
@xenjke  I have Adguard Home configured as my DNS server at router level, so any device doing a DNS lookup shows in AGH's logs
