### ISSUE TITLE
Predbat/intelligent go configuration

### ISSUE THREAD

**Issue by PhilPJL** [dan-r/HomeAssistant-Ohme#102]
Do you have a recommended configuration when using Predbat + Ohme + Intelligent Go?

**Comment by dan-r** [comment]
Nothing I can personally recommend as I don't use it, but there's a section in the [predbat documentation](https://springfall2008.github.io/batpred/devices/#ohme) with some pointers in it.

There might be some useful info in #50 and #91 too.
