### ISSUE TITLE
Expose charger voltage as sensor

### ISSUE THREAD

**Issue by andyvee69** [dan-r/HomeAssistant-Ohme#14]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
3 additional sensors
Charger voltage
Charger current
CT clamp current reading

**Describe alternatives you've considered**

**Additional context**

**Comment by dan-r** [comment]
Agreed that charger current and CT clamp reading would be useful.
I'm less sure on voltage, as I believe it is only reported during a charge session, so it seems as if it would spend a lot of time as 'Unknown'. I'll have a play around with it and see I come up with :)

**Comment by andyvee69** [comment]
Voltage is useful for detecting PEN protection under/over voltage conditions. AFAIAA voltage is monitored constantly, I know Ohme can pull logs from the charger regardless of if you are plugged in or not showing voltage

**Comment by dan-r** [comment]
Agreed that its a useful metric. I've just released v0.2.0 which adds a current and CT sensor. Both seem to be working in my (limited) testing.

I'll leave this issue open as I will add voltage, but want to try to find a way to read it constantly first.

**Comment by andyvee69** [comment]
I think the only way of monitoring constantly may be from device logs. Still a useful metric during a session though.

**Comment by dan-r** [comment]
v0.2.2 adds voltage sensor. Let me know if you have any issues. It should report voltage (0 d.p.) during a charge and 'Unknown' when no charge is in progress.
