### ISSUE TITLE
Toggles not updated in Home Assistant when changed in Ohme App

### ISSUE THREAD

**Issue by brutus6** [dan-r/HomeAssistant-Ohme#18]
**Describe the bug**

When you set or unset a toggle option like 'Sleep when inactive' or 'Lock charger buttons' in the Ohme App it is not reflected on the toggles in Home Assistant. Works fine when you set in Home Assistant first and if you then view the Ohme App. 

**To Reproduce**

Edit a toggle in Ohme App and see if the Home Assistant toggles get updated.

**Expected behavior**

I would expect the toggles in both Home Assistant and Ohme to match each other regardless as to whether set in Home Assistant or Ohme App first.

**Screenshots**

![20231229_175314-COLLAGE](https://github.com/dan-r/HomeAssistant-Ohme/assets/131045297/652aa10a-bc46-4341-b0be-bb31c1a885e0)

**Home Assistant Version**

Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Integration Version**

V.0.2.0

**Additional context**

Device info
ePod
by Ohme
Firmware: v2.12

**Comment by dan-r** [comment]
How long are you waiting before checking this in home assistant? It polls the endpoint for those settings every minute, so if you change it in the Ohme app and wait a minute or two it should update.

**Comment by andyvee69** [comment]
Works OK here, a slight delay between changing in Ohme app and HA updating

**Comment by brutus6** [comment]
Sorry. My mistake. You're quite right. It is taking around 50 seconds to update. I didn't realise.

**Comment by dan-r** [comment]
Not a problem, I've [added a section to the README ](https://github.com/dan-r/HomeAssistant-Ohme/blob/dev/README.md) with a bit more info on the refresh cycles. Its just in the dev branch for now but I'll publish it in the next release.
