### ISSUE TITLE
Cannot login to integration when adding

### ISSUE THREAD

**Issue by dmsims** [dan-r/HomeAssistant-Ohme#26]
Unable to login adding integration

Added integartion to HACS then go to Devices and services and add Ohme integration. Dialogue box pop up appears and I enter my Google account details, error message is "Invalid credentials provided."

I should be able to login with this Google account. I have logged in on the Ohme app, and Google (by logging out and logging back in again)

![Screenshot 2024-01-02 105054](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/faf5dfe2-3f37-4b2a-8429-c1a58607c1f2)

**Home Assistant Version**
Core
2023.12.4
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

**Integration Version**
v0.2.6

**Comment by dan-r** [comment]
(Currently) the integration doesn't support social account login so you'll need to use an Ohme account. You should be able to set a password for your account thought the settings page of the Ohme app, or by using 'reset password'. 

I initially created my account using Google but was able to login after doing this.

**Comment by dmsims** [comment]
Switched to email account - works :) - thanks

**Comment by andyvee69** [comment]
> Switched to email account - works :) - thanks

If you are on IOG you will need to do the disconnect device procedure in the Octopus app and go through the onboarding process again

**Comment by dmsims** [comment]
I disconnected the charger and now get this when I scan the QR code :(

![1704198293168](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/fd755531-2714-450d-96c7-af69c2a32664)

**Comment by andyvee69** [comment]
Why are you scanning the charger QR code in the Octopus app? You need to go through the onboarding process again - the charge for less tile from the homepage of the Octopus app.

**Comment by dmsims** [comment]
My only excuse is that (like a lot of things) things have been moved/renamed

The tile is now called "Intelligent Octopus Go For EVs"

Thanks for the integration - all sorted now
