### ISSUE TITLE
Charger online/offline status

### ISSUE THREAD

**Issue by andyvee69** [dan-r/HomeAssistant-Ohme#30]
**Is your feature request related to a problem? Please describe.**
Ability to create an alert if charger goes offline

**Describe the solution you'd like**
Binary sensor for online/offline status

**Describe alternatives you've considered**

**Additional context**

**Comment by dan-r** [comment]
Seems doable. When we do the API call for the CT reading one of the fields which comes back is:
`clampReadingAt: 1704276225190`
(or converted) `clampReadingAt: 2024-01-03T10:03:45.190Z`

I could do a binary sensor so:
If we haven't heard from the charger in over a minute, assume its down?

**Comment by andyvee69** [comment]
Is there not an API field for online/offline or a heartbeat? Not all chargers support CT clamps, and if they do they aren't always fitted.

**Comment by dan-r** [comment]
There is indeed. There's an 'online' boolean field in the same response. I'll put that in

**Comment by andyvee69** [comment]
Excellent

**Comment by dan-r** [comment]
All done and v0.3.0 up. Would you mind testing it out a bit and reporting back? Should update every minute.

**Comment by andyvee69** [comment]
Appears to work fine, seems to be a slight lag but that is fine, that's probably at the Ohme end anyway

**Comment by dan-r** [comment]
Good to hear, I'll close this for now, re-open it if you have any more issues.

Dan
