### ISSUE TITLE
Incorrect values in some sensors

### ISSUE THREAD

**Issue by dmsims** [dan-r/HomeAssistant-Ohme#34]
Car is unlugged (my wife has taken it to work at 7.40am - time now 12.02pm) some sensors show incorrect values e.g.

Power Draw 2,000W
Current Draw 8.1A
Car connected Plugged in

**Expected behavior**
Sensors should be zero or correct value

**Screenshots**
![Screenshot 2024-01-04 113354](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/b2e2c8e2-dae5-460f-837b-b8ef6fb9c01b)

**Home Assistant Version**
Core
2024.1.0
Supervisor
2023.12.0
Operating System
11.2
Frontend
20240103.3

**Integration Version**
v0.3.1

**Additional context**
Using Chrome on Windows 11 - Refresh, shift Refresh or closing HA tab and reopening a new HA tab does not change the values

**Comment by dan-r** [comment]
Can you double check the version please? I'd expect to see the 'Charger Online' sensor if on 0.3.1 (unless you've disabled/hidden it of course). 

Could you also check that the Ohme app is reporting values correctly and if you have any errors in the home assistant log.

**Comment by dan-r** [comment]
Looks like a lot of network errors from other integrations - are you getting updates on anything? (VW and Octopus, for example).

**Comment by brutus6** [comment]
The Ohme app screenshot you have posted suggests that Ohme thinks the car is still plugged in. Worth trying to reboot the Ohme charger? Not sure if that will fix it, but you shouldn't see the complete screen if the car is unplugged.

**Comment by dan-r** [comment]
Good spot @brutus6, hadn't noticed that

**Comment by andyvee69** [comment]
> The Ohme app screenshot you have posted suggests that Ohme thinks the car is still plugged in.

It does indeed. It should show 'Not Plugged In' at the top of the screen. I would power the Ohme off for 10 minutes at the fusebox, looks like it is offline.

**Comment by dmsims** [comment]
Cycled the charger for 10 mins

![1704373602946](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/72999882-f2bb-413a-96dd-db50a8ea03eb)

The Charger online sensor in the integration updated correctly:

![Screenshot 2024-01-04 130818](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/e375bd34-a929-440b-9baa-568ef73e3dfa)

The Ohme app still shows exactly the same screen (even killed it and restarted)
Charger shows as online in app

![Screenshot_2024-01-04-13-20-03-752_io ohme android](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/dc294291-a85c-4e03-89b9-4afa8c580744)

**Comment by andyvee69** [comment]
You may have to plug in and unplug for it to reset the status

**Comment by dmsims** [comment]
I went and looked at the actual charger (but the app still showed it as being plugged in)

As soon as I plugged the car in the Ohme screen changed to "Smart charging" and all the values in the integration returned to those expected

![1704382628483](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/a8cd0148-41f9-4cc0-b54c-61bd226a8fa6)

**Comment by dan-r** [comment]
If its all working for now I'll close this down and put it down to an API issue.

Dan
