### ISSUE TITLE
Failed to turn on - session not found in database

### ISSUE THREAD

**Issue by jon798** [dan-r/HomeAssistant-Ohme#35]
When trying to turn on the charger from the switch in the card on the dashboard in HA, the error below is presented and it fails to turn on:

Failed to call service homeassistant/turn_on. Ohme API response error: /v1/chargeSessions/ohmeapaaaaaa/stop, 404; {"timestamp":1704524149903,"status":404,"error":"Not Found","message":"Session with ID ohmeapaaaaaa not found in DB. Ended meanwhile?","path":"/v1/chargeSessions/ohmeapaaaaaa/stop"}

Note that this is when there is no car connected, I was just trying to experiment with changing settings from HA vs in the Ohme app.  Also may be relevant that we have been without a car for a while as the old one went back and the new one is yet to arrive. The last charge session available in the Ohme app was 10th December.

(I have changed the last 6 letters of the device ID to aaaaaa just in case).

Thanks,

Jon.

**Comment by dan-r** [comment]
Which switch are you using? Looks like the pause charge one?

**Comment by jon798** [comment]
It's the "main" switch - I assumed that would link/unlink the integration to Ohme's servers (as opposed to doing anything specific to a charger):
<img width="346" alt="image" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/74460995/8324eb41-e09e-4234-a899-98dde3f72b78">
(hopefully the image uploads)

**Comment by dan-r** [comment]
That's a card-specific switch which turns all the switches within it on/off. It's not part of the integration, but I believe you can remove the switch in the card configuration.

**Comment by jon798** [comment]
Well, that's a new thing learned today!
I've turned off "show header toggle" on the card; will experiment with the individual switches, but I would expect trying to pause a charge when charging isn't happening would throw an error, so that now all makes sense..

Thanks,
Jon.
