### ISSUE TITLE
Question regarding the "Charge Slot Active" sensor, although could be a bug 

### ISSUE THREAD

**Issue by gb095666** [dan-r/HomeAssistant-Ohme#36]
I have just had a new Ohme ePod installed.

All the sensors seem to be working, however last night the "Charge Slot Active" sensor didn't seem to behaved how I thought it should, but I maybe wrong.

In the Ohme app I have set up a schedule which states add 80% by 06:00 everyday

I plugged the car in at 18:40 yesterday and the Ohme app gave me a slot from 21:15 until 5:57 the next morning, so I would expect the "Charge Slot Active" to change to "On" at 21:15 and "Off" at 5:57 however as you can see below the sensor seemed to flip flop quite a bit, (mainly staying on) until I unplugged the car at 14:16

Charge Slot Active Sensor
8 January 2024
Turned off
14:16:28 - 4 hours ago
Turned on
14:00:28 - 4 hours ago
Turned on
08:19:29 - 10 hours ago
Turned off
08:18:59 - 10 hours ago
Turned on
02:08:29 - 16 hours ago
Turned off
02:07:59 - 16 hours ago
Turned on
01:50:59 - 16 hours ago
Turned off
01:50:29 - 16 hours ago
Turned on
01:45:59 - 16 hours ago
Turned off
01:45:29 - 16 hours ago
7 January 2024
Turned on
21:15:29 - 21 hours ago

**Home Assistant Version**
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0
HACS 1.33.0

[HomeAssistant-Ohme]: v0.3.1

Ohme ePod Firmware: v2.12

I am willing to do any testing required if you want to use me as a guinea pig

**Comment by andyvee69** [comment]
At what time did your car reach 100% and what % was it on when you plugged in?

**Comment by gb095666** [comment]
The car stopped charging at 3.48, I think there was roughly 40% left in the battery when I plugged it in, so I didn't really need 80% charge, I just assumed I could leave it at that as it would cover most situations.

**Comment by andyvee69** [comment]
If you are on IOG then you need to adjust to how much you actually need to Add within 5% or so.

**Comment by gb095666** [comment]
I am on IOG and I appreciate that the charge required should be closer to the amount I need, however I would have thought the "Charge Slot Active" sensor would turn off when the end of the slot was reached, i.e 5.57 in my case, regardless of if the car is fully charged or not ?

My assumption is that the sensor indicates when I am getting offpeak electric, but I maybe wrong, just looking for a bit of clarification really or if the author believes it to be a bug.

**Comment by dan-r** [comment]
The charge slot sensor should be on when you're within an intelligent slot. Basically it looks for an upward slope on the graph on the app Home Screen. Did you get anything in the home assistant logs overnight?

Might be worth enabling debug logs for this integration next time you charge?

**Comment by andyvee69** [comment]
> My assumption is that the sensor indicates when I am getting offpeak electric

Not necessarily. As your car also has to be actively charging. Plus the notification you received initially was not correct - your car would not have been scheduled to charge continuously for that entire time period. That's a bug with the Ohme notification.

**Comment by gb095666** [comment]
I don't remember seeing anything out of the ordinary in the logs, unfortunately I have rebooted my HA this afternoon so cant scroll back to last night now to check.

I will enable debug and take note of the graph the next time I charge the EV and report back, thanks.

**Comment by dan-r** [comment]
> I will enable debug and take note of the graph the next time I charge the EV and report back, thanks.

Thank you, just drop the debug logs here (taking out anything sensitive) when you get a chance. It looks like it could be a communication issue, but even if so it still shouldn't do this.

**Comment by gb095666** [comment]
> > My assumption is that the sensor indicates when I am getting offpeak electric
> 
> Not necessarily. As your car also has to be actively charging. Plus the notification you received initially was not correct - your car would not have been scheduled to charge continuously for that entire time period. That's a bug with the Ohme notification.

Thanks for the clarification.
Like a lot of people I am trying to automate things during offpeak slots, I obviously know the standard 11:30 to 05:30, but I want to utilise any extra car charging slots so thought that sensor would be the correct one.

Just one question to further my understanding, if the car stops charging due to either it being full or Octopus pausing for a while, will that have any affect on what charging period I am in i.e. Peak or Offpeak ? (obviously outside of the standard offpeak period)

**Comment by dan-r** [comment]
@gb095666 had any more issues with this or a chance to collect debug logs?

**Comment by gb095666** [comment]
I tried it again last night and this time is appeared to work, although I did notice an odd issue with how the sensors worked, I am just pulling all the logs and screenshots together and will post them in a zip file when I have them

**Comment by gb095666** [comment]
Here is the zip file containing the logs etc, hopefully you can understand the data, but if not let me know
[Ohme Integration.zip](https://github.com/dan-r/HomeAssistant-Ohme/files/13891018/Ohme.Integration.zip)

**Comment by dan-r** [comment]
Thanks for sending that over, I've had a look through and it all seems to be how I'd expect in this instance. The power draw API reading is a bit... quirky, and something I need to document. #13 has more info. 

Basically: The power readings returned by the API are what appears to be a 5 minute moving average, so the charging binary sensor has some additional logic to make it react quicker, mainly for the case of coordinating other loads and for solar/battery storage automations. If a charge slot has just ended and the power draw has dropped significantly, it's interpreted as a charge stopping, which is pretty much always the case. 

The flip flopping you saw before shouldn't happen though, so I'd be interested to see if you could recreate that.

**Comment by gb095666** [comment]
Thanks for going through the data and reporting back, I will see if I can recreate the flip flopping and pass back any details.
