### ISSUE TITLE
social logins

### ISSUE THREAD

**Issue by nraimo1** [dan-r/HomeAssistant-Ohme#37]
any eta on social logins?

**Comment by dan-r** [comment]
AFAIK this is pretty much impossible without cooperation from Ohme, as I'd need to implement proper SSO and follow effectively the same flow as linking Octopus to Ohme for example. 

That would be my preferred way of doing auth as it's a lot better than saving the credentials in Home Assistant storage like what I do now.

**Comment by dan-r** [comment]
@nraimo1 I don't use twitter but feel free to email me, address is on my GitHub profile.
