### ISSUE TITLE
Added the intergration and OHME log in details which succeeded but no device found

### ISSUE THREAD

**Issue by Leecavturbo** [dan-r/HomeAssistant-Ohme#38]
**Describe the bug**
As title 

**To Reproduce**
Added via hacs

**Expected behavior**
To see a state, charging or kw etc 

**Screenshots**

**Home Assistant Version**
Find this in Settings > About.

Home Assistant Core 2024.1.2

**Integration Version**
Find this from HACS.
No info given by the intergration

**Additional context**
Install via custom repository went as expected without error. Restarted HA and OHME now showing . Opened to be asked for OHME email and password which entered and succeeded message. No device or entity listed

**Comment by dan-r** [comment]
Could you please fill in every field in the issue and include debug logs and some additional context.

**Comment by Leecavturbo** [comment]
![IMG_6207](https://github.com/dan-r/HomeAssistant-Ohme/assets/116071327/8e2d7aec-e91b-4c7c-8e2f-3319147ae951)
![IMG_6208](https://github.com/dan-r/HomeAssistant-Ohme/assets/116071327/6ce2dfc2-bf60-4af8-8c8c-0727a0c05b41)

**Comment by dan-r** [comment]
Any errors in the Home Assistant log?

May be worth enabling debug logs for the integration - click on it from the screenshot you showed and there should be an option to enable debug logs. After enabling, restart home assistant then disable debug logs from the same place and it should give you a log file. Could you please provide this - redacting any personal information if necessary. 

That should give me more of an idea as to why it isn't working. 

Could you also please share what charger you have and verify that the login details are for the same account by logging out of the Ohme app and using the same credentials to log in. It is possible if you initially created your account using a social account that you could have duplicate accounts.

**Comment by Leecavturbo** [comment]
> Any errors in the Home Assistant log?
> 
> May be worth enabling debug logs for the integration - click on it from the screenshot you showed and there should be an option to enable debug logs. After enabling, restart home assistant then disable debug logs from the same place and it should give you a log file. Could you please provide this - redacting any personal information if necessary. 
> 
> That should give me more of an idea as to why it isn't working. 
> 
> Could you also please share what charger you have and verify that the login details are for the same account by logging out of the Ohme app and using the same credentials to log in. It is possible if you initially created your account using a social account that you could have duplicate accounts. 

No errors pre or post debug in system log . You need log from supervisor?
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/116071327/7696349b-1a7f-44e8-b27a-910160744308)

**Comment by Leecavturbo** [comment]
I deleted the charger in OHME intergration first. Reset password even though it was never a social password. Logged out and back in on OHME app with new password.
Add entry to which success /configuration created message.
Still no charger 
Oh it is an OHME pro.
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/116071327/9e4810be-78e1-4d3f-983e-0af39cc4bbc1)

**Comment by dan-r** [comment]
With debug logging turned on you should see a lot of messages in the log, as it puts one out with every request it makes. I haven't any experience with the supervisor setup but you may need to take a look in there to see the debug messages. 

It's also possible that there's a compatibility issue with the version of home assistant you're running, I'll give it a test over the weekend.

**Comment by dan-r** [comment]
@Leecavturbo have you had any luck finding the debug logs/narrowed down the issue at all?

**Comment by Leecavturbo** [comment]
I’ve not gone away so will try find time to get it

**Comment by ryamoo** [comment]
@dan-r I'm having the same issue. 
Debug logging, repeated error is: 
`TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'`

Debug log attached. I've removed what looks like my user id and device ID, can send you the log directly if you needed those. 
I enabled debug logging, deleted the "Ohme Charger" entry in the integration, then re-added it with my account details, gave it a moment and reloaded the page, turned off debug logging. 
[home-assistant_ohme_2024-01-18T13-32-48.816Z.log](https://github.com/dan-r/HomeAssistant-Ohme/files/13977242/home-assistant_ohme_2024-01-18T13-32-48.816Z.log)

**Comment by dan-r** [comment]
@ryamoo which version of home assistant are you using?

**Comment by ryamoo** [comment]
> @ryamoo which version of home assistant are you using?

2023.9.1 - didn't realise I was so far behind! I'll update and try again, unless you want me to try something on this version?

**Comment by dan-r** [comment]
I haven't tested that far back but looks like that error could be fixed by updating. I'd say try updating and try again
