### ISSUE TITLE
Ability to control pre-condition options

### ISSUE THREAD

**Issue by 3shirts** [dan-r/HomeAssistant-Ohme#41]
The only feature I would love to be able to control and currently can't in the precondition option. It would be ace if I could automate that based on weather.

A switch entity for pre-conditioning and a number entity for the minutes of preconditioning would be great if they can be accessed in the API.

**Comment by dan-r** [comment]
You read my mind - I was just thinking about this today. 

I was thinking of implementing it like the charge target/time is. So if you aren't charging it changes the schedule, if you are it changes the current session.

**Comment by 3shirts** [comment]
Yep, that's what I was imagining.

On a related note: Is there a way to implement an option so we can choose to just _always_ change the first schedule even if it's actively charging? Changing the active session messes with the Intelligent Octopus Go tariff so it would be a good safety net if I could select to never do that.

**Comment by dan-r** [comment]
@3shirts I've implemented both of your suggestions in [v0.4.0-beta.1](https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v0.4.0-beta.1). Would you mind testing them out? You may need to [follow this](https://hacs.xyz/docs/faq/beta/) to update to beta.

Preconditioning input should be quite self explanatory. 0 = off, 1+ = the time to precondition for.

The 'Never update an ongoing session' option is visible if you go to Devices & Services > Ohme > Configure and should ensure that the ongoing session is never updated.

I haven't had a chance to test extensively but all feedback is welcome!

**Comment by 3shirts** [comment]
Thanks. I've updated and it looks like it's working (the changes are reflected in the Ohme app) but I haven't tried an actual charge yet. I'll let you know.
