### ISSUE TITLE
Price cap enable/disable?

### ISSUE THREAD

**Issue by andyvee69** [dan-r/HomeAssistant-Ohme#45]
**What happened?**
Price cap field shows a value and I have price cap turned off. Is there a switch for price cap enable/disable?

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Log Output**
Any relevant logs from Home Assistant.

**Home Assistant Version**
Find this in Settings > About.

**Integration Version**
Find this from HACS.

**Additional context**

**Comment by dan-r** [comment]
The price cap value is set regardless of whether you have the price cap turned on or off (Enable Price Cap switch). Even if you change this, it'll still stay turned off.

If you don't want to see the entity, you should just be able to disable it at the Home Assistant level?

**Comment by andyvee69** [comment]
That's my point, there is no enable price cap switch?

**Comment by dan-r** [comment]
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/77725593-781c-472a-9c0e-9089dc2a7492)

Do you not see this on your end?

**Comment by andyvee69** [comment]
No. But just done another restart and it has appeared. Odd.
