### ISSUE TITLE
Ability to capture smart schedule

### ISSUE THREAD

**Issue by RaptorG** [dan-r/HomeAssistant-Ohme#47]
**Is your feature request related to a problem? Please describe.**
Ohme sends a smart schedule for time slots. Some of these time slots are outside of peak hours. 

**Describe the solution you'd like**
Ability read these slots.

**Describe alternatives you've considered**
Ohme sends these as push notifications, is it possible to receive notification in HA integration and parse them

**Additional context**
knowing additional smart slots would help in automating to disable PV battery outside of Off peak hours.

**Comment by RaptorG** [comment]
Thanks for your response. Sorry I don't know python much so its mostly French and Greek to me.

Assuming Octopus provide upto 5 smart slots then additional 4 sensors can be set with a value of Unavailable , Not Allocated, Off or Unknown.   
Something like 
sensor.ohme_next_slot [the earliest slot ]
sensor.ohme_2nd_slot
sensor.ohme_3rd_slot
sensor.ohme_4th_slot
sensor.ohme_5th_slot

I have enabled history on Android notifications for Ohme App so I can see how many slots do they usually assign.
Might I suggest taking a look at https://github.com/megakid/ha_octopus_intelligent. BTW this integration doesn't work with Ohme.

**Comment by dan-r** [comment]
The problem is that AFAIK the number of slots is effectively unlimited, and I've seen screenshots listing 10+ slots. You'd then need a start and an end for each slot. 

Maybe a text sensor with a comma seperated list? Eg:
`00:30-02:00, 02:30-03:00, 04:00-05:30`
I guess it depends how you're planning to use the info

**Comment by RaptorG** [comment]
That should do. I don't yet know how but should be possible to parse text sensor values. E.g. Values between comma as
slot_1_start> time_value and slot_1_end> time_value 
slot_2_start> time_value and slot_2_end> time_value 
slot_3_start> time_value and slot_3_end> time_value 
and so on and do something at that time.

Basically, I have an PV battery, which I would like to stop draining which is easy enough during Off Peak. During Peak I can read Power Draw  or Car Charging or Charge Slot Active sensor state. e.g. if power draw is above 0 and car charging is on then disable battery discharge. Enable discharge when the sensors flip.

If the slot time is known then it would be possible to charge battery on AC and reliably stop as well. Am I making it more complicated than it should be?

**Comment by dan-r** [comment]
I'm not too sure in your specific case - I'd have given up at: do x when charge slot active :) 

I've made a start on the charge slots sensor in v0.4.3-beta.2 ([beta instructions](https://hacs.xyz/docs/faq/beta/)). Mind testing it out?

<img width="555" alt="Screenshot 2024-01-26 at 11 31 23" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/ca6efcee-4db6-4dd0-a448-0947b5e72f46">

**Comment by RaptorG** [comment]
If it helps. I have Eddi and Harvi [myenergi solar diverter] with 3 CT clamps. The 3rd CT clamp is on the EV Circuit and set to Battery Storage Only. It can sense the current when EV is charging.  However, it somewhat unreliable as quite often Ohme wakes up, resulting in current draw going up and down. I don't have a problem detecting when EV is charging  or not but haven't been able to fine tune base line current draw when EV is not charging, causing triggers when EV is not charging. Not a huge problem in itself but it triggers EV not charging routines randomly.

**Comment by dan-r** [comment]
I've been trying it out over my past couple of charges and seems to be reliable. Let me know how you get on. 

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/09c99183-0b74-4c02-8e5f-5af5b5d28869)

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/1e06993c-2aac-4637-a9e5-661e10c5f983)

**Comment by RaptorG** [comment]
I can now see the slots. I am yet to figure out what's the best way to utilise these and charge battery during these slots. 
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/44742200/d5474794-216a-4155-9afc-278bcaf2d18b)
