### ISSUE TITLE
Mimic ‘planned_dispatches’

### ISSUE THREAD

**Issue by jeldwendean** [dan-r/HomeAssistant-Ohme#51]
**Is your feature request related to a problem? Please describe.**

As I play around with Predbat I’m realising that it wants to use the Octopus Energy sensors for Intelligent Octopus and it does this because it can plan charges of the home battery during charge slots. It would be good to be able to mimic that functionality within the Ohme integration.

**Describe the solution you'd like**

Maybe the slots could be displayed as an attribute of array called planned_dispatches under the Charge Slot Active sensor (which I believe is like the Intelligent Dispatching sensor). We have the Charge Slots sensor but this wouldn’t work as Predbat wants it in the same format as it’s provided by the Octopus Energy integration.

I’m aware I’m asking to mirror some of the OE functionality here but it could help out other users with Ohme and IO using Predbat.

**Describe alternatives you've considered**

I haven’t yet!

**Additional context**

https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/intelligent/

**Comment by dan-r** [comment]
Have you seen the new(ish) charge slots sensor? This might do what you're needing?

**Comment by jeldwendean** [comment]
I have yeah but it looks like it picks up the planned_dispatches attribute so maybe I try and create my own sensor that can do this off the back of the Charge Slots sensor but not sure how complicated that would be?

**Comment by dan-r** [comment]
Not sure as I've never tried :) 

I'm a bit hesitant to use attributes as from what I've read they shouldn't be used for anything that should be given its own sensor

**Comment by jeldwendean** [comment]
Hmmm ok let’s close this then and I’ll try and work out a way of satisfying the requirements. At the moment Predbat knows if it’s going to charge by using the Car Connected sensor but it assumes that the car will be charging the whole off-peak period and won’t know if it’s going to charge at say 9pm for whatever reason Octopus give me some early slots. It also knows when it’s currently charging based on the Car Charging sensor. I just need to find a way of feeding it the slots so it’s got an idea of when the car could potentially charge. Out of the box it just uses the OE HA integration but that doesn’t work for us Ohme users.

**Comment by dan-r** [comment]
I'll close this one down and happy to look into requirements for this use case on #50. 

In terms of the planned_dispatches attribute, it should be doable using template sensors - happy to take it a look with you privately if you get stuck, feel free to drop an email.
