### ISSUE TITLE
Slots didn’t update

### ISSUE THREAD

**Issue by jeldwendean** [dan-r/HomeAssistant-Ohme#56]
**What happened?**
It looks like Ohme wanted to charge my car later on but the slots weren’t refreshed. The slots given were 23:30 to 5:30 but the car charged until 7:27.

![IMG_1518](https://github.com/dan-r/HomeAssistant-Ohme/assets/104971277/b17fbdbe-3aa5-4be2-8d1b-5cb13c071063)
![IMG_1517](https://github.com/dan-r/HomeAssistant-Ohme/assets/104971277/b9a9214f-c391-430c-93c6-36d2fe8d03b8)
![IMG_1516](https://github.com/dan-r/HomeAssistant-Ohme/assets/104971277/411dd17b-beea-4235-acca-50191e756153)
![IMG_1519](https://github.com/dan-r/HomeAssistant-Ohme/assets/104971277/726eeb88-0e60-40b0-a0a8-7505b0f67844)

**To Reproduce**

Plug in as normal

**Expected behavior**

Slots should update if they change

**Log Output**

N/A

**Home Assistant Version**

2024.1.5

**Integration Version**

0.6.1

**Additional context**

**Comment by dan-r** [comment]
Ah yes - so currently we don't re-evaluate the charge slots unless the schedule changes as there's some weird behaviour towards the end of the charge. I'll take this out and see how far I get with it.

**Comment by dan-r** [comment]
Just to keep you updated, I'm trying out a fix for this tonight

**Comment by jeldwendean** [comment]
@dan-r yeah I've noticed that they're now updating so I think we can close this and if I see it happen again I'll raise a new issue 😄
