### ISSUE TITLE
Octopus cheap rate 30 minute binary sensor

### ISSUE THREAD

**Issue by maegibbons** [dan-r/HomeAssistant-Ohme#59]
Hi, thanks for this excellent integration.  I use the Ohme pro with Intelligent Octopus Go.

What I would like to see is a seperate binary sensor for "if within half hour Octopus intelligent charging slot".

The slots that come through from octopus via ohme start and end on 15 minute boundaries.

However,  Octopus bill based on half hour/30 min slots. I.e the MINIMUM slot is 30 minutes and i would like to trigger charging of home batteries for the full half hour not just the 15 min EV charging slot because the 30 minutes is all at cheap rate.

Therefore, I would like a sensor so that if we have a ohme EV slot scheduled between say 19:00 and 19:15 that that "octopus_in_cheap_slot" sensor is true for the full half hour. I.e. 19:00  to 19:30.

Krs

Mark

**Comment by dan-r** [comment]
With my Ohme I find that 90% of the time charge slots tend to be on half hour boundaries. The easiest way to do this may be with an automation in home assistant?

**Comment by maegibbons** [comment]
Hmm... interesting.  For me I would say at least 50% are on 15 minute boundaries.   

It could be done as an automation.  Just felt that it would be easier in python within the integration where you are holding state.

There are cases such as the 2nd 15 minute block in 30 mins that one has to assume that the charge will take place and not be cancelled.

In the cancellation instance the sensor would have to go false.

If that's a definate NO from you then I will try and pursue it in pyscript and this request can be closed.

Many thanks

Mark

**Comment by maegibbons** [comment]
![Screenshot_20240211_180321_Ohme.jpg](https://github.com/dan-r/HomeAssistant-Ohme/assets/11791217/ff930ef6-9d45-48ec-93d7-06ab8c76271a)

**Comment by dan-r** [comment]
@maegibbons I'm looking into implementing this, just haven't had the time to give it a go yet. I'll leave this open and keep you updated

**Comment by jeldwendean** [comment]
Predbat will assume the whole :00 or :30 slot is 7.5p even if the slot is 00:15 or 00:45 so maybe look into that? It would save you a lot of time writing manual automations (and it now works with this integration, just replace the Octopus Energy sensors in the yaml file with the ones from this integration)

**Comment by maegibbons** [comment]
Umm....

I don't really want or need predbat to be honest.

Just an extension to this integration to give a sensor for the whole 30 mins.

But thanks for the suggestion.

Krs

Mark

**Comment by dan-r** [comment]
I haven't come up with an elegant way to achieve this which isn't otherwise solved easier using automations/scripting or something like predbat, so can't prioritise it at the moment. I always welcome contributions if anyone else gets a chance to look at implementing it though.

**Comment by townsmcp** [comment]
Just adding this here in case it helps @maegibbons.
So after a fair bit of research, tying various AI implementations for help (Gemini, ChatGPT, Claude 3.5), I ended up going through a lot of rubbish but finally have a working sensor that does just what you want (I wanted a sensor to do the same as well to use in automations eg turning on/off peak electric recording) - this was thanks to Claude 3.5 Sonnet (which I have seen a fair few people give good reviews for HA help) which I have access to in Perplexity.AI (thanks to a free year via O2 Priority). I know a lot of people dont like using AI for code generation however this has worked for every scenario I have thrown at it. As well as the new sensor, I asked for debugging code that I could run and amended for various scenarios in Dev Tools -> Template so I have included this as well. @dan-r  not sure if you can use any of this to create a sensor to include in the integration?

### Core Features
- Processes time slots from Ohme EV charger integration
- Converts time slots to rounded half-hour boundaries
- Handles multiple slots per day
- Manages overnight periods
- Graceful handling of unavailable/unknown states

### Time Rounding Rules
**Start Times:**
- Before :30 → rounds down to :00 (e.g., 16:25 → 16:00)
- After :30 → rounds to :30 (e.g., 16:45 → 16:30)

**End Times:**
- Before :30 → rounds to :30 (e.g., 22:15 → 22:30)
- After :30 → rounds up to next hour (e.g., 22:35 → 23:00)

### Error Handling
- Manages unavailable sensor states
- Handles unknown states
- Validates time slot formats
- Manages overnight period edge cases

### **Debugging code**
```
{# Configuration - Change these values to test different scenarios #}
{% set test_time = '21:50' %}
{% set test_slots = '21:45-22:15' %}  {# Try different scenarios #}

{# Processing Logic #}
{% set debug = namespace(info=[], is_active=false) %}

{# Add test configuration to debug info #}
{% set debug.info = debug.info + ["Test Configuration:"] %}
{% set debug.info = debug.info + ["  Test Time: " ~ test_time] %}
{% set debug.info = debug.info + ["  Test Slots: " ~ test_slots] %}
{% set debug.info = debug.info + [""] %}

{% if test_slots in ['unavailable', 'unknown'] %}
  {% set debug.info = debug.info + ["Sensor State: " ~ test_slots] %}
  {% set debug.info = debug.info + ["Processing skipped due to invalid sensor state"] %}
  {% set debug.is_active = false %}
{% else %}
  {% set debug.info = debug.info + ["Slot Analysis:"] %}
  
  {% for slot in test_slots.split(', ') %}
    {% set start_time, end_time = slot.split('-') %}
    
    {# Round start time down to hour if before :30, else round to :30 #}
    {% set start_hour = start_time.split(':')[0]|int %}
    {% set start_minute = start_time.split(':')[1]|int %}
    {% if start_minute < 30 %}
      {% set rounded_start = '%02d:00' % start_hour %}
    {% else %}
      {% set rounded_start = '%02d:30' % start_hour %}
    {% endif %}
    
    {# Round end time up to next hour if after :30, else round to :30 #}
    {% set end_hour = end_time.split(':')[0]|int %}
    {% set end_minute = end_time.split(':')[1]|int %}
    {% if end_minute > 30 %}
      {% set rounded_end = '%02d:00' % ((end_hour + 1) % 24) %}
    {% else %}
      {% set rounded_end = '%02d:30' % end_hour %}
    {% endif %}
    
    {# Convert all times to minutes for comparison #}
    {% set current_minutes = test_time.split(':')[0]|int * 60 + test_time.split(':')[1]|int %}
    {% set start_minutes = rounded_start.split(':')[0]|int * 60 + rounded_start.split(':')[1]|int %}
    {% set end_minutes = rounded_end.split(':')[0]|int * 60 + rounded_end.split(':')[1]|int %}
    
    {# Add detailed slot analysis #}
    {% set debug.info = debug.info + ["  Slot " ~ loop.index ~ ":"] %}
    {% set debug.info = debug.info + ["    Original Time Range: " ~ slot] %}
    {% set debug.info = debug.info + ["    Rounded Time Range: " ~ rounded_start ~ " - " ~ rounded_end] %}
    {% set debug.info = debug.info + ["    Current Time (minutes): " ~ current_minutes] %}
    {% set debug.info = debug.info + ["    Start Time (minutes): " ~ start_minutes] %}
    {% set debug.info = debug.info + ["    End Time (minutes): " ~ end_minutes] %}
    
    {% if start_minutes > end_minutes %}
      {% if current_minutes >= start_minutes or current_minutes <= end_minutes %}
        {% set debug.is_active = true %}
        {% set debug.info = debug.info + ["    Status: ACTIVE (Overnight slot)"] %}
      {% else %}
        {% set debug.info = debug.info + ["    Status: inactive (Overnight slot)"] %}
      {% endif %}
    {% else %}
      {% if current_minutes >= start_minutes and current_minutes <= end_minutes %}
        {% set debug.is_active = true %}
        {% set debug.info = debug.info + ["    Status: ACTIVE (Same day slot)"] %}
      {% else %}
        {% set debug.info = debug.info + ["    Status: inactive (Same day slot)"] %}
      {% endif %}
    {% endif %}
    {% set debug.info = debug.info + [""] %}
  {% endfor %}
{% endif %}

{# Final Results #}
{% set debug.info = debug.info + ["Final Result:"] %}
{% set debug.info = debug.info + ["  Charging Active: " ~ debug.is_active] %}

{# Output #}
{{ debug.info | join('\n') }} 
```

### **The code**
The Ohme integration charge slots sensor that I use is `sensor.ohme_home_go_charge_slots`
```
template:
  - binary_sensor:
      - name: "EV Charging Active Period Rounded"
        unique_id: ev_charging_active_period_rounded
        state: >-
          {% set slots = states('sensor.ohme_home_go_charge_slots') %}
          {% if slots == 'unavailable' or slots == 'unknown' %}
            {{ false }}
          {% else %}
            {% set now_time = now().strftime('%H:%M') %}
            {% set ns = namespace(is_active=false) %}
            {% for slot in slots.split(', ') %}
              {% set start_time, end_time = slot.split('-') %}
              
              {# Round start time down to hour if before :30, else round to :30 #}
              {% set start_hour = start_time.split(':')[0]|int %}
              {% set start_minute = start_time.split(':')[1]|int %}
              {% if start_minute < 30 %}
                {% set rounded_start = '%02d:00' % start_hour %}
              {% else %}
                {% set rounded_start = '%02d:30' % start_hour %}
              {% endif %}
              
              {# Round end time up to next hour if after :30, else round to :30 #}
              {% set end_hour = end_time.split(':')[0]|int %}
              {% set end_minute = end_time.split(':')[1]|int %}
              {% if end_minute > 30 %}
                {% set rounded_end = '%02d:00' % ((end_hour + 1) % 24) %}
              {% else %}
                {% set rounded_end = '%02d:30' % end_hour %}
              {% endif %}
              
              {# Convert all times to minutes for comparison #}
              {% set current_minutes = now_time.split(':')[0]|int * 60 + now_time.split(':')[1]|int %}
              {% set start_minutes = rounded_start.split(':')[0]|int * 60 + rounded_start.split(':')[1]|int %}
              {% set end_minutes = rounded_end.split(':')[0]|int * 60 + rounded_end.split(':')[1]|int %}
              
              {% if start_minutes > end_minutes %}
                {% if current_minutes >= start_minutes or current_minutes <= end_minutes %}
                  {% set ns.is_active = true %}
                {% endif %}
              {% else %}
                {% if current_minutes >= start_minutes and current_minutes <= end_minutes %}
                  {% set ns.is_active = true %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {{ ns.is_active }}
          {% endif %}
        attributes:
          current_time: "{{ now().strftime('%H:%M') }}"
          slots: "{{ states('sensor.ohme_home_go_charge_slots') }}"
          sensor_state: >-
            {% if states('sensor.ohme_home_go_charge_slots') in ['unavailable', 'unknown'] %}
              {{ states('sensor.ohme_home_go_charge_slots') }}
            {% else %}
              valid
            {% endif %}
```

**Comment by maegibbons** [comment]
Very interesting.

Thanks for sharing.

I may have a go with this.

Krs

Mark

**Comment by townsmcp** [comment]
@maegibbons maybe try out the debugging code to see if it works for you. So far I'm happy with it but I am more in observer mode rather than relying on automations to change electric tariff just now
