### ISSUE TITLE
Energy Page Integration 

### ISSUE THREAD

**Issue by rory-89** [dan-r/HomeAssistant-Ohme#65]
Great app and like others have mentioned it’s a great way to stop your house battery dumping into the car. 

One thing I’m struggling to get set up and not sure if it’s possible is how to show the Ohme charger on the Home Assistant Energy tab. I feel like the components are all there but the only option I see is for the session amount. As I don’t charge everyday that doesn’t work for me. 

Is there a solution I’m missing here please?

Thanks!

**Comment by dan-r** [comment]
@rory-89 have you had a chance to test this?

**Comment by xenjke** [comment]
I'm also trying to set this up. The Energy tab, when adding an Individual device, requires a sensor:

> Select the energy sensor that measures the device's energy usage in either of GJ, kWh, MJ, MWh, Wh.

so only the `ohme.session_energy` is showing up, but I see it is going negative, and can't really be used to monitor the "in moment" consumption.

Ideally, we'd need the Power Draw sensor, accumulated in `kWh` on short intervals, to be reliably added to the Energy monitoring page. Currently, the Power Draw is `W/kW`.

<img width="546" alt="image" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/8233435/a0e41ffb-ad65-407c-bbd7-85534f88fa96">

**Comment by dan-r** [comment]
@xenjke the energy dashboard requires an energy sensor (Wh/kWh), not a power one (W/kW). The session specific energy sensor is the correct sensor to use for this, but as you point out it currently seems to go negative due to it resetting to 0. I think I know how to resolve that so will try and put out a fix tomorrow.

**Comment by andyvee69** [comment]
@xenjke @dan-r 

If you set a utility meter up in Home Assistant using the session energy sensor.

Then perform a charge so the utility meter now has some data

Then add the utility meter to the energy dashboard in HA

**Comment by andyvee69** [comment]
![Screenshot_2024-03-22-08-10-27-273_io homeassistant companion android](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/3ee09a9d-4562-47cc-81b5-3b7b12ac0ab8)

**Comment by xenjke** [comment]
I was literally doing the same thing yesterday but the utility didn’t show
up in the list of available sensors as the car was already charged by the
time, so I’m going to try this on the next session.

Thank you for your help and suggestion.


--
Andrey

**Comment by andyvee69** [comment]
It won't show until it has some data. Do a charge, and you may have to leave it 24hrs as well

**Comment by dan-r** [comment]
I've just released v0.7.2-beta.1, which changes the state class of the energy sensor to total_increasing.
This should do the same thing as the periodic resetting option @andyvee69 shared, but remove the need to use the utility meter.

**Comment by dan-r** [comment]
I've released v0.7.2 (#68) today which (in my testing) allows you to use the session energy usage sensor as-is with the energy dashboard.
I'll close this issue for now but please open a new issue if anyone has any issues with it.

Dan
