### ISSUE TITLE
Charge session times in GMT not BST after DST change

### ISSUE THREAD

**Issue by andyvee69** [dan-r/HomeAssistant-Ohme#69]
Charge session times are displayed in GMT not BST after DST change last night

**Comment by dan-r** [comment]
Beat me to it!

**Comment by andyvee69** [comment]
Ha ha

**Comment by dan-r** [comment]
@andyvee69 I've just released [v0.8.0-beta.1](https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v0.8.0-beta.1) which should fix this. It seemed as if only the charge slots sensor was affected - the next slot ones were fine already.

@jeldwendean (or someone else who uses predbat) - could you please check that the timezone stuff works fine with predbat?

**Comment by jeldwendean** [comment]
I probably won't need to plug in until Wednesday but will update and let you know

**Comment by jeldwendean** [comment]
Looks good to me! Sorry I was late before you merged 😄
