### ISSUE TITLE
Price cap doesn't support setting price cap limits under 1p (such as 0.1, or -3)

### ISSUE THREAD

**Issue by x00r** [dan-r/HomeAssistant-Ohme#72]
**What happened?**
When trying to set the price cap to under 1p, (such as 0.1p, 0p, or -3p) the value is rejected as being out of range:

> Failed to call service number/set_value. Value 0.1 for number.ohme_price_cap is outside valid range 1 - 100

**To Reproduce**
In the Price Cap field, try to enter any value less than 1

**Expected behavior**
Tiny and/or negative values should be accepted (matching the behaviour of the Ohme app, which is perfectly happy with this)

**Home Assistant Version**
_Core_
2024.4.1
_Supervisor_
2024.04.0
_Operating System_
12.1
_Frontend_
20240404.1

**Integration Version**
v0.8.0

**Additional context**
Such small and/or negative price cap values are very useful for the Octopus Agile tariff (enables charging only at free/nearly-free times or times when you will be paid).

Worth noting the integration does seem to support *reading* values <1 from the Ohme charger if set in the official Ohme app (if you set 0.1p or -1p via the Ohme app, for instance, it will show up correctly in the integration shortly after).

**Comment by dan-r** [comment]
I've adjusted the bounds to -100 to 100 (from 1 to 100). Would you mind testing out v0.8.1-beta.1? ([HACS beta instructions](https://hacs.xyz/docs/faq/beta/))

**Comment by x00r** [comment]
Works flawlessly! Thank you very much, that's perfect.

**Comment by dan-r** [comment]
Good news - I've released that under v0.8.1
