### ISSUE TITLE
Slot Active sensor incorrect state

### ISSUE THREAD

**Issue by HnabrU** [dan-r/HomeAssistant-Ohme#80]
**What happened?**
'binary_sensor.ohme_slot_active' keeps 'ON' despite car charging stopped.

I have 2 x EVs (none of them using APIs), Octopus IOG integrated via Ohme Home Pro EVSE, GivEnergy inverter and battery. I use Predbat HA integration to manage all these. Whenever I use either of EVs I seem to have false info re active slots (despite slot times being visible in Ohme integration correctly). Below is an example from yesterday. Car plugged in around 19:00, given slots by IOG, finished active charging at 21:49, but 'ohme_slot_active' still active until 22:45 when I physically disconnected the car from EVSE (see screenshots). This causes the Predbat integration to work incorrectly as 'ohme_slot_active' sensor is a source of various automations like charging/discharging home battery.

Screenshots:
Ohme app IOG slots notification:
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/160080380/87e47b93-80a6-47d6-8628-8119a70275c7)

Relevant Ohme integration indications after IOG slots received:
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/160080380/fa4f1a3b-d452-4dc1-8eb6-19673eeddd85)

Ohme integration idications more than 30 minutes after car finished charging (NB. Charge Slot Active still ON):
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/160080380/62a953ad-d80f-4d6a-adf6-7d2362ae342d)

'binary_sensor.ohme_slot_active' history for 08/05/24 (NB. active state changed to OFF almost 1 hr after car stopped charging only becasue I unplugged the car):
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/160080380/219f70b1-817b-4bf4-9226-011e83332db4)

'binary_sensor.ohme_car_charging' shows correctly when car finished active charging:
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/160080380/a59d51e6-ea6c-49bb-8d32-6e7ff412e6ab)

**Expected behavior**
Slot Active sensor sets to 'OFF' when car charging stops and 30-minutes slots (i.e. XX:00 or XX:30) finishes.

**Log Output**
Any relevant logs from Home Assistant.

**Home Assistant Version**
Core 2024.5.2, OS 12.3

**Integration Version**
Ohme integration v0.8.2
HACS 1.34.0

**Additional context**
Ohme Home Pro FW 2.62 (it was th same with 1.22 I had before)

**Comment by dan-r** [comment]
Thanks for reporting this issue. I'll see if I can recreate in my next couple of charges...

**Comment by dan-r** [comment]
Should be fixed under v0.9.0. If you still have issues please reopen this. 

Dan
