### ISSUE TITLE
Upgrade to HA Core 2024.7.0 gives "Detected code that calls async_forward_entry_setup for integration ohme with title"

### ISSUE THREAD

**Issue by gb095666** [dan-r/HomeAssistant-Ohme#82]
**What happened?**
Upgraded HA core from 2024.6.4, after reboot got the early warning error message in the system log

**To Reproduce**
Upgrade to HA Core 2024.7.0

**Expected behavior**
Message is an early warning that as of 2025.1 the function will not be acceptable 

**Log Output**
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 21:34:40 (6 occurrences)
Last logged: 21:34:42

Detected code that calls async_forward_entry_setup for integration ohme with title: Ohme Charger and entry_id: 2a816906d41f774edfeae2d72bc9dc06, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Home Assistant Version**
Find this in Settings > About.

**Integration Version**
Core - 2024.7.0
Supervisor - 2024.06.2
Operating System - 12.4
Frontend - 20240703.0

**Additional context**
Early warning only, the integration is still working.

**Comment by dan-r** [comment]
Would you mind testing this beta please? Should be fixed.

https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v0.8.4-beta.1

**Comment by gb095666** [comment]
Yes, that looks to have fixed it, the error message no longer appears, thanks for the swift response,
