### ISSUE TITLE
charger charging when not wanted

### ISSUE THREAD

**Issue by Begie1605** [dan-r/HomeAssistant-Ohme#85]
Hey All, i don't believe this is a bug....but wanted to share to see if someone has ideas on how to handle..

When i arrive at home, and plug in the car following happens in an automation:
- when at home, when electricity tariff is normal....put on pauze.
- when tariff changes to low, resume (always around 21:00 hours except in weekends)
- when tariff changes to normal, pause charging (always around 07:00h on weekdays), except when i'm not working home today (other helper) then continue charging...

This works fine, so when working at home one day, charging stops around 07:00 (as i normally don't need the car that day).

But then somewhere during the day the pause state changes, and app tells me session ended...
also then sometime later, it starts charging again...
These last 2 actions have nothing to do with automations, but i presume that you can only set ohme to pause for x time....and that depending on the departure time it starts charging again (i already tried different departure times etc....but  has no results).

Can this departure time be removed, so it does not start charging when i don't want.
Ideal scenario would be that the day i'm working home....when tariff changes to low it simply continue to charge...

If anyone has some ideas why it starts charging on its own....please share...

**Comment by dan-r** [comment]
So I believe a few hours after the charge session ends, Ohme will start a new one. As far as I know that's not configurable and sadly beyond the scope of this integration. 

I'd recommend emailing Ohmes technical support - they seem quite helpful.
