### ISSUE TITLE
Target Percentage changes not updating in the app

### ISSUE THREAD

**Issue by elsatim** [dan-r/HomeAssistant-Ohme#86]
**What happened?**
When using v1 of the ohme app, I was able to adjust the charge percentage of a single schedule by changing the target Percentage in home assistant. Now changes are not related

**Expected behavior**
When the target charge % is adjusted in home assistant I was expecting it to change in one of the schedules in the ohme V2 app. The only change currently is to update what the % is set to in the app, which is reflected in hass

**Home Assistant Version**
2024.7.0
**Integration Version**
1.0.0

**Comment by dan-r** [comment]
From the [documentation](https://github.com/dan-r/HomeAssistant-Ohme#entities), the three number inputs (percentage, time and pre-conditioning time) act as follows:

`If in a charge session, these change the active charge. If disconnected, they change your first schedule`

The exception to this is if ["Never update an ongoing session"](https://github.com/dan-r/HomeAssistant-Ohme#options) is enabled in the configuration screen, in which case the first schedule will always be updated regardless of whether you are in a charge.

**Comment by elsatim** [comment]
Unfortunately when I change the amount before approving the charge, the % from the routine is used not the target set in hass. If I change the target after approving the charge it adjusts the session. For what I need it to do I can adjust my automation but didn't feel like correct behaviour
