### ISSUE TITLE
Max chars for Charge Slots

### ISSUE THREAD

**Issue by cydalby** [dan-r/HomeAssistant-Ohme#87]
**What happened?**
Charge slots has gone over the max chars allowed `Invalid state with length 271. State max length is 255 characters`

**Log Output**
```Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1205
First occurred: 19:30:50 (198 occurrences)
Last logged: 21:08:59

Failed to set state for sensor.ohme_charge_slots, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1205, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2302, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 239, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 271. State max length is 255 characters.
```

**Home Assistant Version**
2024.7.1

**Integration Version**
1.0.0

**Comment by dan-r** [comment]
I'll take a look at this, thanks for reporting. 

Something I've been meaning to do is to 'flatten' the charge slots as this sensor tends to return eg. 19:00-20:00, 20:00-21:00 if the charge plan is 3kw at first then 7kw for example rather than just 19:00-21:00

**Comment by dan-r** [comment]
I've published [v0.9.1-beta.1](https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v0.9.1-beta.1) which should now collapse consecutive charge slots into 1. Would you mind trying it out? [Beta instructions](https://hacs.xyz/docs/faq/beta/).

So now, for example, if the app shows the slots: 06:00-06:15, 06:15-09:00, 09:00-12:00, 13:00-14:00, the sensor should show: 06:00-12:00, 13:00-14:00. This way the length of the sensor should never get long enough to cause an issue.

**Comment by dan-r** [comment]
@cydalby did you have a chance to try this out?

**Comment by dan-r** [comment]
Closing as fixed, planning to promote from dev to stable this week.
