### ISSUE TITLE
Unknown error occurred during setup (worked once then stopped)

### ISSUE THREAD

**Issue by ErskineTech2** [dan-r/HomeAssistant-Ohme#89]
**What happened?**
suddenly not updating and now wont connect at all from config page with Unknown error occurred.

**To Reproduce**
installed as per the instructions used HACS logged in worked for around 20 minutes then stopped now setup fails with unknown error occurred

**Expected behavior**
id expect it to continue working 

**Log Output**

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 18 August 2024 at 13:20:06 (3 occurrences)
Last logged: 20:33:29

Error setting up entry Ohme Charger for ohme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/__init__.py", line 38, in async_setup_entry
    await async_setup_dependencies(hass, entry)
  File "/config/custom_components/ohme/__init__.py", line 24, in async_setup_dependencies
    await client.async_update_device_info()
  File "/config/custom_components/ohme/api_client.py", line 301, in async_update_device_info
    resp = await self.async_get_account_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/api_client.py", line 295, in async_get_account_info
    resp = await self._get_request('/v1/users/me/account')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/api_client.py", line 157, in _get_request
    await self._handle_api_error(url, resp)
  File "/config/custom_components/ohme/api_client.py", line 110, in _handle_api_error
    raise ApiException(msg)
custom_components.ohme.api_client.ApiException: Ohme API response error: /v1/users/me/account, 401; 

**Home Assistant Version**
2024.8.2

**Integration Version**
V0.9.0

**Additional context**
suspect the 401 correct login but denied access is relevent

**Comment by ErskineTech2** [comment]
Hi Dan, 
thanks for getting back to me yes the Ohme app works iv reset my password again to insure im not doing something stupid 
![image](https://github.com/user-attachments/assets/86f5b07f-605e-497e-9f3e-dbf100d089a2)
this is 100% my correct username and password having just set it 5 minutes ago and logged into the app 

cheers
Jason

**Comment by ErskineTech2** [comment]
I have completely removed and reinstalled the integration and its now working crossing my fingers it was just some weird install issue

**Comment by ErskineTech2** [comment]
and now its stopped again 
![image](https://github.com/user-attachments/assets/2ae9fd21-148f-4618-a631-c6ff81439120)

**Comment by ErskineTech2** [comment]
thanks for the assist on this Dan i suspect this is my setup if no one else is having issues i can see details now and again so im going to close this off as a issue on my setup rather than with the plugin

**Comment by dan-r** [comment]
Let me know if you come across it again. I've seen similar issues with a flaky internet connections and its on my list to make the integration a bit more tolerant of this.
