### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by Deathstar2001** [dan-r/HomeAssistant-Ohme#90]
Hi, the app is not available in HACS.
Has it moved? 

Cheers

**Comment by dan-r** [comment]
You'll have to add it as a custom repository in HACS. I raised a PR to add the integration to the default repositories list 8 months ago but sadly it doesn't look like the maintainers are merging any of these in anymore. 

https://github.com/hacs/default/pull/2246

**Comment by Deathstar2001** [comment]
Ahh, I mis read that bit. 
All installed and running 👍

**Comment by dan-r** [comment]
Glad to hear it. Please do let me know if you have any issues or come across any bugs. 

Dan
