### ISSUE TITLE
How to get battery SoC from FiatChamp

### ISSUE THREAD

**Issue by murkle** [dan-r/HomeAssistant-Ohme#93]
https://github.com/wubbl0rz/FiatChamp seems to work well to get the SoC from the car's API:
![image](https://github.com/user-attachments/assets/b4c78a3f-5e18-4e13-9d41-7f2dcbef535a)

Is there a way for this plugin to read this? 

thanks 😀

https://github.com/wubbl0rz/FiatChamp/blob/94f72a22784d6c99ef0ef8e16cd50d4396f1eb4f/FiatChampAddon/FiatClient/FiatClient.cs#L196

**Comment by dan-r** [comment]
Looks like this Fiat/Chrysler vehicles, not sure how it would help for Nissans?

**Comment by murkle** [comment]
@dan-r I have a Fiat not a Nissan :)

**Comment by dan-r** [comment]
My apologies - I thought this was an issue for my Nissan integration. 

The car API connectivity isn't something I'd want to add to this integration. If your car is supported by Ohme, you should be able to connect your car through the app and this will show in Home Assistant, but there is currently no way to "feed in" battery percentages to Ohme from elsewhere.

**Comment by dan-r** [comment]
But... It's relatively simple to setup an automation to take say 80% as a static value and subtract the percentage from FiatChamp, and then set the Ohme target to that.

By Googling and using ChatGPT you should get you most of the way there

**Comment by murkle** [comment]
Thanks, was just wondering if there's an easy way to read the car_evInfo_battery_stateOfCharge from FiatChamp directly from the Ohme integration

**Comment by dan-r** [comment]
Sadly not, but if I ever add that sort of integration I'll re-open this
