### ISSUE TITLE
Price Cap removed for Octopus Intelligent Go

### ISSUE THREAD

**Issue by murkle** [dan-r/HomeAssistant-Ohme#94]
Ohme have removed the price cap option. It gives this error when you try to set it.

They say they will "have it temporarily switched back on", but I'm not sure exactly what they mean by that 
![image](https://github.com/user-attachments/assets/76496325-d069-4379-a671-3f3f23177cb0)
![image](https://github.com/user-attachments/assets/48ec2f2f-dfb1-4439-891b-380b3ee493e7)

**Comment by dan-r** [comment]
I've added a check to hide the price cap settings when Ohme reports they're not supported in the [latest beta](https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v1.0.0-beta.1). Could you please try this out and let me know if it all works for you?

[Instructions for installing beta](https://www.hacs.xyz/docs/use/repositories/dashboard/?h=version#downloading-a-specific-version-of-a-repository)

**Comment by murkle** [comment]
Greyed out 👌
![image](https://github.com/user-attachments/assets/25f47598-b05e-48de-887c-687428bc4849)
