### ISSUE TITLE
Ohme auth refresh error on 30 September

### ISSUE THREAD

**Issue by xenjke** [dan-r/HomeAssistant-Ohme#95]
Starting from September 30 at 09:31, I encountered the following error:

```
Ohme auth refresh error: { "error": { "code": 400, "message": "TOKEN_EXPIRED", "status": "INVALID_ARGUMENT" } }
```

When trying to refresh the password in HA oHme settings I got `Unknown error`:

```
500 Internal Server Error
Server got itself in trouble
```

Logging in through https://api.ohme.io/fleet/index.html#/authentication/login also results in a permissions error.

```
Your account does not have sufficient privileges
```

The iOS application works fine though.

I have contacted Ohme support but am currently struggling to go around their scripted replies.
I’m sharing this here for visibility in case anyone else experiences the same issue.

**Comment by dan-r** [comment]
I haven't been able to reproduce this. What version of Home Assistant are you running?

**Comment by xenjke** [comment]
> I haven't been able to reproduce this. What version of Home Assistant are you running?

2024.10.0 but this started to happen in 2024.9 too

**Comment by dan-r** [comment]
Odd. I was on 2024.9.2 but have just updated to the latest stable version (2024.10.1) and will see if anything changes. 

Does the integration work at all for you? I couldn't tell from your description whether you get that error as soon as the integration loads of only after a period of time.

**Comment by xenjke** [comment]
> Odd. I was on 2024.9.2 but have just updated to the latest stable version (2024.10.1) and will see if anything changes.
> 
> Does the integration work at all for you? I couldn't tell from your description whether you get that error as soon as the integration loads of only after a period of time.
> 
> I get the same "Your account does not have sufficient privileges" on that fleet page too, but the app an integration works fine. Weird because that page works perfectly to reset passwords!

The integration is not functioning at all. It throws an error when attempting to update the password during configuration too.

I still haven't received a response from Ohme support regarding this issue.

I'm not sure if this is relevant, but everything started the same night my car's 12V battery died overnight and Hyundai's Bluelink access was throttled for 24 hours. I suspect some of my applications made excessive requests to the Hyundai API, which may have caused the battery to die and possibly blocked the Ohme access token.

**Comment by xenjke** [comment]
Some integration logs when trying to authenticate on the configuration screen.

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 20:10:43 (3 occurrences)
Last logged: 20:16:37

Error setting up entry Ohme Charger for ohme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/__init__.py", line 38, in async_setup_entry
    await async_setup_dependencies(hass, entry)
  File "/config/custom_components/ohme/__init__.py", line 24, in async_setup_dependencies
    await client.async_update_device_info()
  File "/config/custom_components/ohme/api_client.py", line 310, in async_update_device_info
    resp = await self.async_get_account_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/api_client.py", line 304, in async_get_account_info
    resp = await self._get_request('/v1/users/me/account')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/api_client.py", line 159, in _get_request
    await self._handle_api_error(url, resp)
  File "/config/custom_components/ohme/api_client.py", line 112, in _handle_api_error
    raise ApiException(msg)
custom_components.ohme.api_client.ApiException: Ohme API response error: /v1/users/me/account, 401; 
```

**Comment by dan-r** [comment]
Are you still getting this error? I still haven't been able to reproduce it

**Comment by dan-r** [comment]
Glad to hear its working for you now
