### ISSUE TITLE
Solar charging switch

### ISSUE THREAD

**Issue by camhef** [dan-r/HomeAssistant-Ohme#96]
The Ohme app (Android v2.2.2) now offers me **Solar charging** in the _My Charger_ section of the app. It shows a switch for **Solar off** (the default) or **Solar boost**. 
![Screenshot_2024-10-03-15-49-51-19_9cb0f09086f30927a2ccbf7687296e94](https://github.com/user-attachments/assets/02b83840-dc60-4cd3-ab71-e5fafb8048f3)

Are there any plans to expose
this functionality? Ideally it would be good to have a switch in HA to activate/deactivate the option.
Thanks.

**Comment by dan-r** [comment]
I've added this in the [latest beta](https://github.com/dan-r/HomeAssistant-Ohme/releases/tag/v1.0.0-beta.1). Could you please try this out and let me know if it all works for you?

[Instructions for installing beta](https://www.hacs.xyz/docs/use/repositories/dashboard/?h=version#downloading-a-specific-version-of-a-repository)

**Comment by camhef** [comment]
Amazing - this enhancement is **working** within an hour of suggesting it!  When I switch solar chaging on or off in HA it seems that the Ohme app needs to be closed and restarted for the change to show.  That is an issue with the Ohme app, rather than anything related to HA. 

Now all I need is for the sun to shine a bit more this autumn.

**Comment by dan-r** [comment]
Glad to hear its working, you caught me at a good time! :)

I hope to release it as stable in the next few days, once I've had a chance to test the other changes.

Dan
